# Generated by Django 2.2.1 on 2019-09-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_institute_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='picture_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
