# Generated by Django 2.2.6 on 2019-10-16 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190909_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='delegates',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
