# Generated by Django 2.2.6 on 2019-10-16 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_person_delegates'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='managed_institutes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='delegates',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
