# Generated by Django 2.2.6 on 2019-10-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20191016_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_prof',
            field=models.BooleanField(default=False),
        ),
    ]
