# Generated by Django 2.2.6 on 2019-10-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_person_is_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_prof',
            new_name='_is_prof',
        ),
    ]
