# Generated by Django 2.2.6 on 2019-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20191017_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='_is_vice_dean',
            field=models.BooleanField(default=False),
        ),
    ]
