# Generated by Django 2.2.7 on 2020-01-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_person__is_vice_dean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='_is_vice_dean',
            new_name='_is_associate_dean',
        ),
    ]
