# Generated by Django 3.0.2 on 2020-01-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200110_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='picture_url',
        ),
    ]
